language: cpp
dist: trusty
sudo: false
compiler:
    - clang
    - gcc
os:
    - linux

before_script:
    - wget -q -O - http://sourceforge.net/projects/boost/files/boost/1.63.0/boost_1_63_0.tar.gz | tar -xz
    - cd boost_1_63_0 && ./bootstrap.sh --with-libraries=coroutine,system,context,thread,chrono,date_time,atomic
    - ./b2  --ignore-site-config && cd ..
    - mkdir build
    - cd build
    - cmake -DBOOST_ROOT=`pwd`/../boost_1_63_0 -DCMAKE_BUILD_TYPE=Debug ..

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - clang-3.8
    - lcov
#    - libboost-all-dev


script:
    - $CXX --version
    - make
    - make test
    - if [ "$CXX" == "g++-4.9" ]; then make coverage; bash <(curl -s https://codecov.io/bash) -X lcov; fi


install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++"; fi

