language: cpp
dist: trusty
sudo: false
compiler:
    - clang
#    - gcc
os:
    - linux

before_script:
    - wget -q -O - http://sourceforge.net/projects/boost/files/boost/1.63.0/boost_1_63_0.tar.gz | tar -xz
    - mkdir build
    - cd build
    - BOOST_ROOT=`pwd`/../boost_1_63_0 cmake ..

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
#    - g++-5
    - clang-3.8
#    - libboost-all-dev


script:
    - make
    - make test

install:
#    - if [ "$CXX" = "g++" ]; then export CXX="g++" CC="gcc"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++" CC="clang"; fi


