language: cpp
dist: trusty
sudo: false
compiler:
    - clang
    - gcc
os:
    - linux

before_script:
    - wget -q -O - http://sourceforge.net/projects/boost/files/boost/1.63.0/boost_1_63_0.tar.gz | tar -xz
    - mkdir build
    - cd build
    - cmake -DBOOST_ROOT=`pwd`/../boost_1_63_0 ..

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - clang-3.8
    - lcov
#    - libboost-all-dev


script:
    - make
    - make test
    - if [ "$CXX" = "g++" ]; then bredis_coverage; bash <(curl -s https://codecov.io/bash) -X lcov; fi


install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++"; fi

