# Operating system (build VM template)
os: Visual Studio 2017

platform:
#    x64
    - Win32
#configuration: Release

environment:
    BOOST_ROOT: "C:\\Libraries\\boost_1_64_0"
    BOOST_LIBRARYDIR: "C:\\Libraries\\boost_1_64_0\\lib32-msvc-15.0"


before_build:
    - cmake --version
    - echo %BOOST_ROOT%
    - dir "C:\Libraries"
    - dir "%BOOST_ROOT%"
    - ps: wget 'https://github.com/MSOpenTech/redis/releases/download/win-3.0.504/Redis-x64-3.0.504.zip' -OutFile "Redis-x64-3.0.504.zip"
    - '@ECHO redis downloaded deployed'
    - dir
    - 7z x Redis-x64-3.0.504.zip
    - dir
    - set PATH=%APPVEYOR_BUILD_FOLDER%;%PATH%

build_script:
  - cmake -G "Visual Studio 15 2017 Win64" -H. -B_builds -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%"
  - cmake --build _builds

test_script:
  - ps: cd _builds
  - ctest -VV -C "%CONFIG%"
